#!/bin/sh
# Generated by `inka desktop --installer`.
#
# Installs a packaged inka desktop app for the current user. The app's own files
# ship in the tarball beside this script; the shared engine (and, for the cef
# backend, the shared Chromium runtime) are reused when already present in their
# XDG folders, and downloaded from the inka release otherwise.
#
# usage:
#   sh install.sh [--from <dir-or-url>] [--engine-base <url>] [--yes]
#                 [--no-modify-path] [--uninstall]
set -eu

APP_NAME={{APP_NAME}}
APP_ID={{APP_ID}}
BACKEND={{BACKEND}}
RUNTIME={{RUNTIME}}
LAUFEY_VERSION={{LAUFEY_VERSION}}
TARGET={{TARGET}}
APP_VERSION={{APP_VERSION}}
APP_BASE={{APP_BASE}}
INKA_BASE={{INKA_BASE}}
CEF_ARCHIVE={{CEF_ARCHIVE}}
CEF_SHA256={{CEF_SHA256}}

# Color only when stderr is a terminal and NO_COLOR is unset.
_red=""; _yellow=""; _cyan=""; _reset=""
if [ -t 2 ] && [ -z "${NO_COLOR:-}" ]; then
    _red='\033[1;31m'; _yellow='\033[1;33m'; _cyan='\033[36m'; _reset='\033[0m'
fi
info() { printf "${_cyan}info${_reset}: %s\n" "$*" >&2; }
warn() { printf "${_yellow}warning${_reset}: %s\n" "$*" >&2; }
die() { printf "${_red}error${_reset}: %s\n" "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

usage() {
    cat <<EOF
$APP_NAME installer (version $APP_VERSION)

usage: sh install.sh [options]

options:
      --from <dir-or-url>  where to find $APP_NAME.tar.gz (default: beside this script)
      --engine-base <url>  inka release base for the shared engine/CEF runtime
      --no-modify-path     do not edit shell rc files
  -y, --yes                non-interactive (accepted for compatibility)
      --uninstall          remove the app (leaves the shared engine/runtime)
  -h, --help               show this help
EOF
}

# Fetch <base>/<file> into <dest>; <base> may be an http(s) URL or a local dir.
fetch() {
    _base=$1; _file=$2; _dest=$3
    case "$_base" in
        http://*|https://*)
            if have curl; then
                if [ "${_base#https://}" != "$_base" ]; then
                    curl --proto '=https' --tlsv1.2 -fsSL "$_base/$_file" -o "$_dest"
                else
                    curl -fsSL "$_base/$_file" -o "$_dest"
                fi
            elif have wget; then
                if [ "${_base#https://}" != "$_base" ]; then
                    wget --https-only -qO "$_dest" "$_base/$_file"
                else
                    wget -qO "$_dest" "$_base/$_file"
                fi
            else
                die "need curl or wget to download over HTTP"
            fi
            ;;
        *) cp "$_base/$_file" "$_dest" ;;
    esac
}

# Like fetch, but draws curl/wget progress on a TTY.
download() {
    _base=$1; _file=$2; _dest=$3
    case "$_base" in
        http://*|https://*)
            _tty=0
            if [ -t 2 ] && [ -z "${NO_COLOR:-}" ]; then _tty=1; fi
            if have curl; then
                if [ "${_base#https://}" != "$_base" ]; then
                    if [ "$_tty" = 1 ]; then
                        curl --proto '=https' --tlsv1.2 -fLS --progress-bar "$_base/$_file" -o "$_dest"
                    else
                        curl --proto '=https' --tlsv1.2 -fsSL "$_base/$_file" -o "$_dest"
                    fi
                else
                    if [ "$_tty" = 1 ]; then
                        curl -fLS --progress-bar "$_base/$_file" -o "$_dest"
                    else
                        curl -fsSL "$_base/$_file" -o "$_dest"
                    fi
                fi
            elif have wget; then
                if [ "${_base#https://}" != "$_base" ]; then
                    if [ "$_tty" = 1 ]; then
                        wget --https-only --show-progress -O "$_dest" "$_base/$_file"
                    else
                        wget --https-only -qO "$_dest" "$_base/$_file"
                    fi
                else
                    if [ "$_tty" = 1 ]; then
                        wget --show-progress -O "$_dest" "$_base/$_file"
                    else
                        wget -qO "$_dest" "$_base/$_file"
                    fi
                fi
            else
                die "need curl or wget to download over HTTP"
            fi
            ;;
        *) cp "$_base/$_file" "$_dest" ;;
    esac
}

sha256_of() {
    if have sha256sum; then
        sha256sum "$1" | awk '{print $1}'
    elif have shasum; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        die "no sha256sum or shasum available"
    fi
}

verify_sha() {
    _file=$1; _sidecar=$2
    _expected=$(awk '{print $1}' "$_sidecar" | head -1 | tr 'A-F' 'a-f')
    _actual=$(sha256_of "$_file" | tr 'A-F' 'a-f')
    [ "$_expected" = "$_actual" ] || die "checksum mismatch for $(basename "$_file"): expected $_expected, got $_actual"
}

# Directory holding this script (for a local, beside-the-script tarball).
self_dir() {
    case "$0" in
        */*) (cd "$(dirname "$0")" && pwd) ;;
        *) pwd ;;
    esac
}

add_path_block() {
    case ":$PATH:" in *":$BIN:"*) return 0 ;; esac
    _block="# >>> inka apps initialize >>>
export PATH=\"$BIN:\$PATH\"
# <<< inka apps initialize <<<"
    _wrote=0
    for _rc in "$HOME/.profile" "$HOME/.bashrc" "$HOME/.zshrc"; do
        [ -e "$_rc" ] || continue
        if ! grep -q '>>> inka apps initialize >>>' "$_rc" 2>/dev/null \
            && ! grep -q '>>> inka initialize >>>' "$_rc" 2>/dev/null; then
            printf '\n%s\n' "$_block" >> "$_rc"
            info "added $BIN to PATH in $_rc"
            _wrote=1
        fi
    done
    if [ "$_wrote" = 0 ] && [ ! -e "$HOME/.profile" ]; then
        printf '%s\n' "$_block" > "$HOME/.profile"
        info "added $BIN to PATH in $HOME/.profile"
    fi
}

remove_path_block() {
    for _rc in "$HOME/.profile" "$HOME/.bashrc" "$HOME/.zshrc"; do
        [ -e "$_rc" ] || continue
        if grep -q '>>> inka apps initialize >>>' "$_rc" 2>/dev/null; then
            _tmp="$_rc.inka-apps.$$"
            sed '/# >>> inka apps initialize >>>/,/# <<< inka apps initialize <<</d' "$_rc" > "$_tmp"
            mv "$_tmp" "$_rc"
            info "removed the $APP_NAME PATH block from $_rc"
        fi
    done
}

# ---- args -------------------------------------------------------------------
FROM=""
ENGINE_BASE=""
MODIFY_PATH=1
UNINSTALL=0
while [ $# -gt 0 ]; do
    case "$1" in
        --from) FROM="${2:?--from needs a value}"; shift ;;
        --engine-base) ENGINE_BASE="${2:?--engine-base needs a value}"; shift ;;
        --no-modify-path) MODIFY_PATH=0 ;;
        -y|--yes) ;;
        --uninstall) UNINSTALL=1 ;;
        -h|--help) usage; exit 0 ;;
        *) die "unknown option '$1' (try --help)" ;;
    esac
    shift
done

# ---- platform + paths -------------------------------------------------------
_os=$(uname -s 2>/dev/null || echo unknown)
_arch=$(uname -m 2>/dev/null || echo unknown)
[ "$_os/$_arch" = "Linux/x86_64" ] || die "unsupported platform '$_os/$_arch' (only Linux/x86_64 is published)"

DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
BIN="$HOME/.local/bin"
APPS="$DATA/inka/apps/$APP_ID"
ENGINE_DIR="${INKA_RUNTIME_HOME:-$DATA/inka/runtime}"
CEF_DIR="${INKA_CEF_HOME:-$DATA/cef/$LAUFEY_VERSION/$TARGET}"
APP_TARBALL="$APP_NAME.tar.gz"

if [ "$UNINSTALL" = 1 ]; then
    rm -rf "$APPS"
    rm -f "$BIN/$APP_NAME"
    rm -f "$DATA/applications/$APP_ID.desktop"
    rm -f "$DATA/icons/hicolor/512x512/apps/$APP_ID.png"
    remove_path_block
    info "uninstalled $APP_NAME"
    exit 0
fi

# ---- resolve bases ----------------------------------------------------------
if [ -n "$FROM" ]; then
    APP_SRC="$FROM"
elif [ -n "$APP_BASE" ]; then
    APP_SRC="$APP_BASE"
else
    APP_SRC=""
fi

BASE="$INKA_BASE"
if [ -n "$ENGINE_BASE" ]; then BASE="$ENGINE_BASE"; fi
if [ -n "${INKA_RELEASE_BASE:-}" ]; then BASE="$INKA_RELEASE_BASE"; fi

TMP=$(mktemp -d "${TMPDIR:-/tmp}/inka-app.XXXXXX")
trap 'rm -rf "$TMP"' EXIT INT TERM

# ---- fetch the app tarball --------------------------------------------------
if [ -n "$APP_SRC" ]; then
    info "fetching $APP_TARBALL from $APP_SRC"
    download "$APP_SRC" "$APP_TARBALL" "$TMP/$APP_TARBALL"
    fetch "$APP_SRC" "$APP_TARBALL.sha256" "$TMP/$APP_TARBALL.sha256" \
        || die "cannot read $APP_TARBALL.sha256 from $APP_SRC"
    verify_sha "$TMP/$APP_TARBALL" "$TMP/$APP_TARBALL.sha256"
else
    _dir="$(self_dir)"
    for _cand in "$_dir/$APP_TARBALL" "$PWD/$APP_TARBALL"; do
        [ -f "$_cand" ] || continue
        cp "$_cand" "$TMP/$APP_TARBALL"
        break
    done
    [ -f "$TMP/$APP_TARBALL" ] || die "cannot find $APP_TARBALL; pass --from <dir-or-url>"
fi

# ---- shared engine ----------------------------------------------------------
if [ -f "$ENGINE_DIR/libinka_runtime-$RUNTIME.so" ]; then
    info "engine $RUNTIME already installed"
else
    info "installing engine $RUNTIME from $BASE"
    mkdir -p "$ENGINE_DIR"
    download "$BASE" "libinka_runtime-$RUNTIME.so" "$TMP/engine.so"
    fetch "$BASE" "libinka_runtime-$RUNTIME.so.sha256" "$TMP/engine.so.sha256" \
        || die "cannot read the engine checksum from $BASE"
    verify_sha "$TMP/engine.so" "$TMP/engine.so.sha256"
    cp "$TMP/engine.so" "$ENGINE_DIR/libinka_runtime-$RUNTIME.so"
fi

# ---- shared CEF runtime (cef backend) ---------------------------------------
if [ "$BACKEND" = cef ]; then
    _want="v$LAUFEY_VERSION $TARGET"
    _have=""
    [ -f "$CEF_DIR/.installed" ] && _have=$(cat "$CEF_DIR/.installed" 2>/dev/null || true)
    if [ "$_have" = "$_want" ] && [ -f "$CEF_DIR/libcef.so" ]; then
        info "shared CEF runtime $LAUFEY_VERSION already installed"
    else
        info "installing shared CEF runtime $LAUFEY_VERSION from $BASE"
        download "$BASE" "$CEF_ARCHIVE" "$TMP/$CEF_ARCHIVE"
        printf '%s\n' "$CEF_SHA256" > "$TMP/cef.sha256"
        verify_sha "$TMP/$CEF_ARCHIVE" "$TMP/cef.sha256"
        mkdir -p "$TMP/cef"
        tar -xzf "$TMP/$CEF_ARCHIVE" --no-same-owner --no-same-permissions -C "$TMP/cef"
        rm -f "$TMP/cef/laufey" "$TMP/cef/.downloaded"
        rm -rf "$TMP/cef/extensions"
        [ -f "$TMP/cef/libcef.so" ] || die "$CEF_ARCHIVE did not contain libcef.so"
        rm -rf "$CEF_DIR"
        mkdir -p "$(dirname "$CEF_DIR")"
        mv "$TMP/cef" "$CEF_DIR"
        printf '%s\n' "$_want" > "$CEF_DIR/.installed"
    fi
fi

# ---- install the app --------------------------------------------------------
info "installing $APP_NAME $APP_VERSION"
mkdir -p "$DATA/inka/apps"
rm -rf "$APPS"
mkdir -p "$APPS"
tar -xzf "$TMP/$APP_TARBALL" --no-same-owner --no-same-permissions -C "$APPS"
chmod 0755 "$APPS/$APP_NAME"
[ -f "$APPS/$APP_NAME.so" ] && chmod 0755 "$APPS/$APP_NAME.so"

# Link the shared CEF runtime next to the launcher (laufey's RPATH is
# `.:$ORIGIN` and CEF reads its resources from there). chrome-sandbox is copied
# for real: Chromium security-checks that helper.
if [ "$BACKEND" = cef ]; then
    for _e in "$CEF_DIR"/*; do
        [ -e "$_e" ] || continue
        _n=$(basename "$_e")
        case "$_n" in extensions) continue ;; esac
        if [ "$_n" = "chrome-sandbox" ]; then
            cp -f "$_e" "$APPS/$_n"
        else
            rm -f "$APPS/$_n"
            ln -s "$_e" "$APPS/$_n"
        fi
    done
fi

# ---- desktop integration ----------------------------------------------------
mkdir -p "$BIN" "$DATA/applications"
ln -sfn "$APPS/$APP_NAME" "$BIN/$APP_NAME"
cat > "$DATA/applications/$APP_ID.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=$APP_NAME
Exec=$APPS/$APP_NAME
Icon=$APP_ID
StartupWMClass=$APP_ID
Categories=Utility;
EOF
if [ -f "$APPS/AppIcon.png" ]; then
    _icons="$DATA/icons/hicolor/512x512/apps"
    mkdir -p "$_icons"
    cp -f "$APPS/AppIcon.png" "$_icons/$APP_ID.png"
fi
[ "$MODIFY_PATH" = 1 ] && add_path_block

info "$APP_NAME installed at $APPS"
info "launch with: $BIN/$APP_NAME"
case ":$PATH:" in
    *":$BIN:"*) ;;
    *) [ "$MODIFY_PATH" = 1 ] && info "restart your shell, or run: . \"$HOME/.profile\"" ;;
esac
