[package]
name = "inka-format"
license = "MIT"
version = "0.8.1"
edition = "2021"
publish = false

[dependencies]

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_Threading",
] }
